version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://localhost:3001
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - banking-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - JWT_SECRET=your-secret-key-here
      - DB_TYPE=json
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - banking-network

networks:
  banking-network:
    driver: bridge

volumes:
  frontend_node_modules:
  backend_node_modules: